version: "2.3"
services:
  ansible:
    container_name: sample-ansible
    image: willhallonline/ansible:2.9-alpine
    volumes:
      - $PWD:/app
    working_dir: /app
    tty: true
    network_mode: host
    command: /bin/sh
